package com.mojagap.mojanode.infrastructure;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * All System environment variables must be kept here for auditing purpose
 */
@AllArgsConstructor
@Getter
public enum EnvironmentVariable {
    MOJA_NODE_JWT_SECRET_KEY("MOJA_NODE_JWT_SECRET_KEY"),
    JWT_EXPIRATION_TIME_MINUTES("JWT_EXPIRATION_TIME_MINUTES"),
    MOJA_NODE_SERVER_PORT("MOJA_NODE_SERVER_PORT"),
    MOJA_NODE_DB_HOST("MOJA_NODE_DB_HOST"),
    MOJA_NODE_DB_PORT("MOJA_NODE_DB_PORT"),
    MOJA_NODE_DB_USERNAME("MOJA_NODE_DB_USERNAME"),
    MOJA_NODE_DB_PASSWORD("MOJA_NODE_DB_PASSWORD"),
    MOJA_NODE_DB_NAME("MOJA_NODE_DB_NAME"),
    AWS_MOJA_NODE_SECRET_KEY("AWS_MOJA_NODE_SECRET_KEY"),
    AWS_MOJA_NODE_ACCESS_KEY("AWS_MOJA_NODE_ACCESS_KEY"),
    AWS_MOJA_NODE_REGION("AWS_MOJA_NODE_REGION"),
    ENVIRONMENT("ENVIRONMENT"),
    AWS_ENABLED("AWS_ENABLED"),
    AWS_TEST_S3_BUCKET("AWS_TEST_S3_BUCKET"),
    AWS_DEVELOPMENT_S3_BUCKET("AWS_DEVELOPMENT_S3_BUCKET"),
    AWS_PRODUCTION_S3_BUCKET("AWS_PRODUCTION_S3_BUCKET");
    private final String value;
}
